Allow to built release-candidate
zeebe-io/zeebe-releaser pull request #119
Opened 2022-09-27 08:32 UTC by Zelldon

I added another event subprocess to allow to build a release candidate. This helps to not find all information by hand, but with that we can use our existing tooling and information we have in the process.

![zeebe_release](https://user-images.githubusercontent.com/2758593/192475892-b7fd05f7-312f-423b-b13a-18f6fcb3930d.png)

2022-09-27 09:48 UTC, Zelldon commented
i updated the PR to build per default an rc which can be used by other teams and the e2e tests.

\cc @deepthidevaki 


![build-release-candidate](https://user-images.githubusercontent.com/2758593/192493938-ef9a19b9-eb2a-46d6-9213-089a695632dd.png)
![zeebe_release](https://user-images.githubusercontent.com/2758593/192493942-d7bdda3c-0a3e-413a-aa08-f7f0a1716c97.png)

2022-09-28 05:30 UTC, saig0 requested changes
@Zelldon thank you for improving the release process. :+1: 

I played with the new process and found a few issues. Please have a look.
I'm happy to have a chat about the comments.

2022-09-28 05:30 UTC, saig0 commented on src/main/resources/zeebe_release.bpmn
> +      <zeebe:subscription correlationKey="=release_branch_name" />
:x: The variable `release_branch_name` is not defined when the process instance is created. As a result, an incident is created. 

The variable is created when completing the form of the task `Create release branch`.

2022-09-28 05:30 UTC, saig0 commented on src/main/resources/build-release-candidate.bpmn
> +    </bpmn:userTask>
:wrench: We could adjust the form to make it more specific for building the release candidate. This is the same for the other user tasks in the process.

I guess that it uses the form `release_trigger_release.form`.

We could change the variable `release_version` to `release_version + "-rc1"`.

2022-09-28 05:30 UTC, saig0 commented on src/main/resources/build-release-candidate.bpmn
> +          <zeebe:input source="= &#34;Hi :wave: team! There is a new Zeebe version &#34; + release_version + &#34; available that you can test against.&#34;" target="data.text" />
:x: We should adjust the Slack message. Currently, we would announce the release version when we just built the release candidate.

2022-09-28 05:30 UTC, saig0 commented on src/main/resources/build-release-candidate.bpmn
> +    </bpmn:callActivity>
:x: Same here. We should adjust the variables. Currently, we would try to release Zeebe process test for the release version that is not released yet.

2022-09-28 05:33 UTC, saig0 commented on src/main/resources/zeebe_release.bpmn
> +    <bpmn:sequenceFlow id="Flow_1n61zbo" name="No - Alpha release" sourceRef="Gateway_1afx4hl" targetRef="Gateway_15n27wl" />
:wrench: We should adjust the name. The path is taken for `alpha` and `patch` releases.

2022-10-14 04:16 UTC, Zelldon commented
I will close this for now and defer to https://github.com/camunda/zeebe/issues/10651

2022-10-14 04:16 UTC, closed without merging